"""Generate booktabs LaTeX tables for the paper from results/*.csv.

Produces files in paper/tables/:
  - headline_sharpe.tex      Mean Sharpe (10 seeds) per method per universe + PSR
  - factor_alphas.tex        FF3/AQR alphas with HAC t-stats for CMD + Crypto
  - llm_ablation.tex         LLM-DHRP vs DHRP head-to-head for DM/EM/CMD
  - hyperparams.tex          Per-universe training hyperparameters
  - cost_sensitivity.tex     Sharpe at 0/5/10/20/50 bps + breakeven

Run:
    python scripts/generate_paper_tables.py

This script is idempotent and only reads CSVs (no model loading).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
TABLES = ROOT / "paper" / "tables"
TABLES.mkdir(parents=True, exist_ok=True)

# Universes in display order
UNIVERSES = ["DM", "EM", "Commodities", "Sectors", "Global", "Factors", "Crypto", "Bonds"]
UNIVERSE_SHORT = {
    "DM": "DM",
    "EM": "EM",
    "Commodities": "CMD",
    "Sectors": "Sect",
    "Global": "Glb",
    "Factors": "Fact",
    "Crypto": "Cry",
    "Bonds": "Bnd",
}

METHODS_DISPLAY_ORDER = [
    "EW", "MV", "MINVAR", "MAXDIV", "RP", "HRP", "DHRP", "LLM_DHRP",
]


def fmt_mean_std(mean: float, std: float | None = None, decimals: int = 3) -> str:
    """Format a number as 'mean' or 'mean$\\pm$std' depending on whether std is given."""
    if pd.isna(mean):
        return "---"
    if std is None or pd.isna(std) or std == 0.0:
        return f"{mean:.{decimals}f}"
    return f"${mean:.{decimals}f}{{\\pm}}{std:.{decimals}f}$"


def fmt_psr(psr: float, threshold: float = 0.95) -> str:
    """Format a Probabilistic Sharpe Ratio with a star if it crosses 0.95."""
    if pd.isna(psr):
        return "---"
    star = "$^{\\ast}$" if psr >= threshold else ""
    return f"{psr:.3f}{star}"


def fmt_alpha(alpha: float, t_stat: float, p_val: float) -> str:
    """Format an annualized alpha with t-stat in parentheses + significance stars."""
    if pd.isna(alpha) or pd.isna(t_stat):
        return "---"
    pct = alpha * 100  # annualized fraction -> percent
    star = ""
    if not pd.isna(p_val):
        if p_val < 0.01:
            star = "$^{\\ast\\ast}$"
        elif p_val < 0.05:
            star = "$^{\\ast}$"
        elif p_val < 0.10:
            star = "$^{\\dagger}$"
    return f"{pct:.1f}\\% ({t_stat:.2f}){star}"


def write_table(path: Path, body: str, label: str = "") -> None:
    path.write_text(body, encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}")


# ---------------------------------------------------------------------
# Table 1: Headline multi-seed Sharpe + PSR per method per universe
# ---------------------------------------------------------------------

def headline_sharpe_table() -> None:
    mean_path = RESULTS / "sharpe_pivot_multiseed_mean.csv"
    std_path = RESULTS / "sharpe_pivot_multiseed_std.csv"
    psr_path = RESULTS / "psr_pivot_multiseed.csv"

    if not mean_path.exists():
        print(f"  SKIP headline_sharpe.tex (missing {mean_path.name})")
        return

    mean_df = pd.read_csv(mean_path, index_col=0)
    std_df = pd.read_csv(std_path, index_col=0) if std_path.exists() else None
    psr_df = pd.read_csv(psr_path, index_col=0) if psr_path.exists() else None

    # Use the universe order from constant; intersect with available columns
    cols = [u for u in UNIVERSES if u in mean_df.columns]
    rows = [m for m in METHODS_DISPLAY_ORDER if m in mean_df.index]

    # Build LaTeX
    n_cols = len(cols)
    col_spec = "l" + "c" * n_cols
    lines = []
    lines.append("% Auto-generated by scripts/generate_paper_tables.py — do not hand-edit")
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Mean$\\pm$std out-of-sample Sharpe across 10 seeds with "
                 "Probabilistic Sharpe Ratio in brackets. Bold marks the best method "
                 "per universe; $\\ast$ marks $\\text{PSR} > 0.95$ (significant at "
                 "5\\% level). Classical baselines (EW, HRP, MV, MINVAR, MAXDIV, RP) "
                 "are deterministic and reported without standard deviation.}")
    lines.append("\\label{tab:headline}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{" + col_spec + "}")
    lines.append("\\toprule")
    lines.append("Method & " + " & ".join(UNIVERSE_SHORT.get(c, c) for c in cols) + " \\\\")
    lines.append("\\midrule")

    # Identify best mean Sharpe per column (for bolding)
    best_per_col = {c: mean_df[c].idxmax() for c in cols if not mean_df[c].isna().all()}

    for m in rows:
        row_cells = []
        for c in cols:
            mean = mean_df.loc[m, c] if (m in mean_df.index and c in mean_df.columns) else np.nan
            std = std_df.loc[m, c] if (std_df is not None and m in std_df.index and c in std_df.columns) else None
            psr = psr_df.loc[m, c] if (psr_df is not None and m in psr_df.index and c in psr_df.columns) else np.nan
            val = fmt_mean_std(mean, std, decimals=3)
            psr_str = fmt_psr(psr) if not pd.isna(psr) else ""
            cell = f"{val} [{psr_str}]" if psr_str else val
            if best_per_col.get(c) == m and not pd.isna(mean):
                cell = "\\textbf{" + cell + "}"
            row_cells.append(cell)
        lines.append(f"{m.replace('_', '-')} & " + " & ".join(row_cells) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    write_table(TABLES / "headline_sharpe.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------
# Table 2: Factor regression alphas (FF3 + AQR for commodities, FF5+Mom for crypto)
# ---------------------------------------------------------------------

def factor_alphas_table() -> None:
    cmd_path = RESULTS / "Commodities_results.csv"
    if not cmd_path.exists():
        print(f"  SKIP factor_alphas.tex (missing {cmd_path.name})")
        return

    df = pd.read_csv(cmd_path)
    # Expected columns: Method, Sharpe, Alpha_ann, Alpha_t, Alpha_p (FF3),
    # plus AQR fields for commodities
    rows = []
    for m in METHODS_DISPLAY_ORDER:
        sub = df[df["Method"] == m]
        if sub.empty:
            continue
        r = sub.iloc[0]
        rows.append({
            "Method": m.replace("_", "-"),
            "FF3 alpha": fmt_alpha(r.get("Alpha_ann", np.nan),
                                   r.get("Alpha_t", np.nan),
                                   r.get("Alpha_p", np.nan)),
            "AQR alpha": fmt_alpha(r.get("AQR_Alpha_ann", np.nan),
                                   r.get("AQR_Alpha_t", np.nan),
                                   r.get("AQR_Alpha_p", np.nan)),
        })

    if not rows:
        print(f"  SKIP factor_alphas.tex (no method rows)")
        return

    lines = []
    lines.append("% Auto-generated by scripts/generate_paper_tables.py")
    lines.append("\\begin{table}[t]")
    lines.append("\\caption{Annualized factor alphas with HAC Newey-West t-statistics "
                 "in parentheses for the commodity universe. "
                 "$^{\\dagger}$\\,$p<0.10$, $^{\\ast}$\\,$p<0.05$, "
                 "$^{\\ast\\ast}$\\,$p<0.01$. Fama-French 3-factor uses "
                 "Mkt-RF, SMB, HML; AQR uses cross-sectional Value and Momentum "
                 "factors from Asness, Moskowitz, and Pedersen (2013).}")
    lines.append("\\label{tab:alphas}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lcc}")
    lines.append("\\toprule")
    lines.append("Method & FF3 $\\alpha$ & AQR $\\alpha$ \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(f"{r['Method']} & {r['FF3 alpha']} & {r['AQR alpha']} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    write_table(TABLES / "factor_alphas.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------
# Table 3: LLM-DHRP vs DHRP ablation
# ---------------------------------------------------------------------

def llm_ablation_table() -> None:
    summary_path = RESULTS / "all_universes_multiseed_summary.csv"
    if not summary_path.exists():
        print(f"  SKIP llm_ablation.tex (missing {summary_path.name})")
        return

    df = pd.read_csv(summary_path)
    # Expect long format with columns: Method, Universe, Sharpe_mean, Sharpe_std, PSR_mean
    rows = []
    for u in ["DM", "EM", "Commodities"]:
        sub = df[df["Universe"] == u]
        if sub.empty:
            continue
        dhrp = sub[sub["Method"] == "DHRP"]
        llm = sub[sub["Method"] == "LLM_DHRP"]
        if dhrp.empty or llm.empty:
            continue
        d = dhrp.iloc[0]
        l = llm.iloc[0]
        delta = l["Sharpe_mean"] - d["Sharpe_mean"]
        rows.append({
            "U": u,
            "DHRP": fmt_mean_std(d["Sharpe_mean"], d.get("Sharpe_std"), 3) +
                    f" [{fmt_psr(d.get('PSR_mean', np.nan))}]",
            "LLM": fmt_mean_std(l["Sharpe_mean"], l.get("Sharpe_std"), 3) +
                   f" [{fmt_psr(l.get('PSR_mean', np.nan))}]",
            "Delta": f"${delta:+.3f}$",
        })

    if not rows:
        print(f"  SKIP llm_ablation.tex (no LLM_DHRP rows)")
        return

    lines = []
    lines.append("% Auto-generated by scripts/generate_paper_tables.py")
    lines.append("\\begin{table}[h]")
    lines.append("\\caption{LLM-DHRP vs.\\ DHRP, multi-seed comparison ($n=10$). "
                 "Sharpe mean$\\pm$std; PSR in brackets. $\\Delta$ is "
                 "LLM-DHRP minus DHRP. Under multi-seed reporting, LLM "
                 "augmentation provides no statistically significant lift in DM/EM "
                 "and \\emph{regresses} significantly in commodities.}")
    lines.append("\\label{tab:llm_ablation}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lccc}")
    lines.append("\\toprule")
    lines.append("Universe & DHRP & LLM-DHRP & $\\Delta$ Sharpe \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(f"{r['U']} & {r['DHRP']} & {r['LLM']} & {r['Delta']} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    write_table(TABLES / "llm_ablation.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------
# Table 4: Per-universe hyperparameters (read from src/data/universe_config.py)
# ---------------------------------------------------------------------

def hyperparams_table() -> None:
    sys.path.insert(0, str(ROOT))
    try:
        from src.data.universe_config import UNIVERSE_DATA_CONFIG
    except Exception as e:
        print(f"  SKIP hyperparams.tex (cannot import universe_config: {e})")
        return

    rows = []
    for u in UNIVERSES:
        cfg = UNIVERSE_DATA_CONFIG.get(u)
        if not cfg:
            continue
        gate_bias = cfg.get("gate_bias_init")
        rows.append({
            "U": u,
            "lookback": cfg.get("lookback_window", "---"),
            "rebalance": cfg.get("rebalance_freq", "---"),
            "depth": cfg.get("tree_depth", "---"),
            "shrinkage": f"$10^{{{int(np.log10(cfg.get('cov_shrinkage', 1e-6))):d}}}$"
                          if cfg.get("cov_shrinkage", 0) > 0 else "---",
            "hrp_lam": f"${cfg.get('hrp_lam_start', 0):.2f}{{\\to}}{cfg.get('hrp_lam_end', 0):.2f}$",
            "gate_bias": f"${gate_bias:.1f}$" if gate_bias is not None else "---",
        })

    lines = []
    lines.append("% Auto-generated by scripts/generate_paper_tables.py")
    lines.append("\\begin{table}[h]")
    lines.append("\\caption{Per-universe hyperparameters used in DHRP-8.}")
    lines.append("\\label{tab:hyperparams}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lcccccc}")
    lines.append("\\toprule")
    lines.append("Universe & Lookback & Rebal & Depth & Cov shrink & "
                 "HRP $\\lambda_{\\text{start}\\to\\text{end}}$ & Text gate bias \\\\")
    lines.append("\\midrule")
    for r in rows:
        lines.append(f"{r['U']} & {r['lookback']} & {r['rebalance']} & {r['depth']} "
                     f"& {r['shrinkage']} & {r['hrp_lam']} & {r['gate_bias']} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    write_table(TABLES / "hyperparams.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------
# Table 5: Transaction-cost sensitivity
# ---------------------------------------------------------------------

def cost_sensitivity_table() -> None:
    cost_path = RESULTS / "DM_cost_sensitivity.csv"
    if not cost_path.exists():
        print(f"  SKIP cost_sensitivity.tex (missing {cost_path.name})")
        return

    df = pd.read_csv(cost_path)
    if "Method" not in df.columns:
        print(f"  SKIP cost_sensitivity.tex (no Method col)")
        return

    cost_cols = [c for c in df.columns if c.startswith("cost_")]
    if not cost_cols:
        print(f"  SKIP cost_sensitivity.tex (no cost columns)")
        return

    methods = [m for m in METHODS_DISPLAY_ORDER if m in df["Method"].values]
    lines = []
    lines.append("% Auto-generated by scripts/generate_paper_tables.py")
    lines.append("\\begin{table}[h]")
    lines.append("\\caption{Transaction-cost sensitivity: out-of-sample Sharpe "
                 "for the developed-markets universe at varying per-trade "
                 "costs. Costs are applied as basis points (bps) of turnover "
                 "per rebalance.}")
    lines.append("\\label{tab:cost_sensitivity}")
    lines.append("\\centering")
    lines.append("\\small")
    col_spec = "l" + "c" * len(cost_cols)
    lines.append("\\begin{tabular}{" + col_spec + "}")
    lines.append("\\toprule")
    headers = [c.replace("cost_", "").replace("bps", " bps") for c in cost_cols]
    lines.append("Method & " + " & ".join(headers) + " \\\\")
    lines.append("\\midrule")
    for m in methods:
        sub = df[df["Method"] == m]
        if sub.empty:
            continue
        r = sub.iloc[0]
        cells = [f"{r[c]:.3f}" if not pd.isna(r[c]) else "---" for c in cost_cols]
        lines.append(f"{m.replace('_', '-')} & " + " & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    write_table(TABLES / "cost_sensitivity.tex", "\n".join(lines) + "\n")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main() -> None:
    print(f"Generating tables in {TABLES.relative_to(ROOT)}/ from {RESULTS.relative_to(ROOT)}/")
    headline_sharpe_table()
    factor_alphas_table()
    llm_ablation_table()
    hyperparams_table()
    cost_sensitivity_table()
    print("Done. Include in paper via \\input{tables/<name>}.")


if __name__ == "__main__":
    main()
